/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandsPanel.java
 *
 * Created on Mar 2, 2012, 1:21:10 AM
 */
package GUI;

import Controllers.BandsAnalyzer;

/**
 *
 * @author FREAK
 */
public class BandsPanel extends javax.swing.JPanel {
    private BandsAnalyzer bandsAnalyzer;
    
    /** Creates new form BandsPanel */
    public BandsPanel() {
        initComponents();
        //bandsAnalyzer = new BandsAnalyzer(this);
        bandsAnalyzer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
